
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'TF2'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'TF2'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  TF2:
    stage:
      +schema: "STAGE"
      +materialized: table
    core:
      +schema: "CORE"
      v_stg:
        +materialized: view
      incremental:
        +materialized: incremental
    mart:
      +schema: "MART"
      +materialized: table
      dim:
        +materialized: table
      fact:
        +materialized: incremental
      bridge:
        +materialized: table
    testing:
      +schema: "TESTING"
      +materialized: table
  dbt_artifacts:
    +schema: artifact_audit # optional, default is your target schema
seeds:
  class_data:
    +enabled: true
    +full_refresh: true


on-run-start: 
  - "{{ dbt_logging_run_level_start() }}" ## ATARBALY: DBT run level Logging start (from macros)
on-run-end: 
  ## - "{{ log_failed_models() }}"  ## ATARBALY: DBT run level Logging failed handling (from macros)
  - "{{ dbt_logging_run_level_end() }}" ## ATARBALY: DBT run level Logging final steps (from macros)
    
    